version: '3.8'

services:
  laxhornet-server:
    build:
      context: .
      target: server
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
